[general]
import = ["/home/mason/.config/alacritty/theme.toml"]

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Q"
mode = "Vi"

[[keyboard.bindings]]
action = "Last"
key = 5
mode = "Vi|~Search"
mods = "Shift"

[selection]
save_to_clipboard = true

[window]
dynamic_padding = true

[window.dimensions]
columns = 80
lines = 25
