[[language]]
name = "php"
language-servers = [ "phpactor" ]

# https://github.com/helix-editor/helix/wiki/External-formatter-configuration#prettier
[[language]]
name = "html"
formatter = { command = 'pnpm', args = ["prettier", "--config", ".prettierrc", "--parser", "typescript"] }

[[language]]
name = "json"
formatter = { command = 'pnpm', args = ["prettier", "--config", ".prettierrc", "--parser", "typescript"] }

[[language]]
name = "css"
formatter = { command = 'pnpm', args = ["prettier", "--config", ".prettierrc", "--parser", "typescript"] }

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "eslint"]
formatter = { command = 'pnpm', args = ["prettier", "--config", ".prettierrc", "--parser", "typescript"] }

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "eslint"]
formatter = { command = 'pnpm', args = ["prettier", "--config", ".prettierrc", "--parser", "typescript"] }

[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "eslint"]
formatter = { command = 'pnpm', args = ["prettier", "--config", ".prettierrc", "--parser", "typescript"] }

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "eslint"]
formatter = { command = 'pnpm', args = ["prettier", "--config", ".prettierrc", "--parser", "typescript"] }

[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

# https://github.com/helix-editor/helix/issues/3231
[language-server.eslint.config]
validate = "on"
experimental = { useFlatConfig = false }
rulesCustomizations = []
run = "onType"
problems = { shortenToSingleLine = false }
nodePath = ""

[language-server.phpactor]
command = "phpactor"
args = [ "language-server" ]

# [language-server.intelephense]
# command = "intelephense"
# args = [ "--stdio" ]
# config = { intelephense = { environment = { shortOpenTag = true } } }
