[[language]]
name = "php"
language-servers = ["psalm", "intelephense"]
auto-format = false
indent = { tab-width = 3, unit = "   " }

[[language]]
name = "sql"
auto-format = false
indent = { tab-width = 3, unit = "   " }

# https://github.com/helix-editor/helix/wiki/External-formatter-configuration#prettier
[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]
formatter = { command = 'npx', args = [
  "prettier",
  "--config",
  ".prettierrc",
  "--parser",
  "typescript",
] }
auto-format = false

[[language]]
name = "json"
formatter = { command = 'npx', args = [
  "prettier",
  "--config",
  ".prettierrc",
  "--parser",
  "typescript",
] }
auto-format = false

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]
formatter = { command = 'npx', args = [
  "prettier",
  "--config",
  ".prettierrc",
  "--parser",
  "typescript",
] }
auto-format = false

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "eslint"]
formatter = { command = 'npx', args = [
  "prettier",
  "--config",
  ".prettierrc",
  "--parser",
  "typescript",
] }
auto-format = false

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "eslint", "tailwindcss-ls"]
formatter = { command = 'npx', args = [
  "prettier",
  "--config",
  ".prettierrc",
  "--parser",
  "typescript",
] }
auto-format = false

[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "eslint"]
formatter = { command = 'npx', args = [
  "prettier",
  "--config",
  ".prettierrc",
  "--parser",
  "typescript",
] }
auto-format = false

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "eslint", "tailwindcss-ls"]
formatter = { command = 'npx', args = [
  "prettier",
  "--config",
  ".prettierrc",
  "--parser",
  "typescript",
] }
auto-format = false

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = false

[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

# https://github.com/helix-editor/helix/issues/3231
[language-server.eslint.config]
validate = "on"
experimental = { useFlatConfig = false }
rulesCustomizations = []
run = "onType"
problems = { shortenToSingleLine = false }
nodePath = ""

[language-server.intelephense]
command = "intelephense"
args = ["--stdio"]

# https://github.com/bmewburn/intelephense-docs/blob/master/installation.md
[language-server.intelephense.config.intelephense]
environment = { shortOpenTag = true }

[language-server.intelephense.config.intelephense.diagnostics]
implementationErrors = false
typeErrors = false
undefinedFunctions = false
undefinedMethods = false
undefinedTypes = false
undefinedVariables = false

[language-server.phpactor]
command = "phpactor"
args = ["language-server"]

[language-server.psalm]
command = "vendor/bin/psalm-language-server"
timeout = 120

[language-server.rust-analyzer.config.check]
command = "clippy"
